name: "Release to Dev"
run-name: "Release and Rollout - <repo-name>-latest"

on:
  workflow_dispatch:

  push:
    branches:
      - "release"
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      K3S_NAMESPACE: misbah
      REPOSITORY_TARGET: <repo-name>
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short git commit SHA for image tagging
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # platforms: linux/amd64,linux/arm64
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          platforms: linux/arm64
          push: true
          tags: ${{env.REPOSITORY_TARGET}}-latest,${{env.REPOSITORY_TARGET}}-${{env.COMMIT_SHA}}
